feat: sp版(仮)のhtml,css追加
kyo-oki/induction-course pull request #22
Opened 2022-01-13 12:54 UTC by kfukumori

SP版のHTMLとCSSです（作成中）

2022-01-14 01:40 UTC, kyosuke-oki-adglobe-co-jp requested changes
スマホ版を作成する際のディレクトリの構造は/spとなることが多いので修正をお願いいたします。
理由としてはこのページを表示する際のURLが見やすくなるからです。
※`students/k_fukumori/task/index_sp.html`より`students/k_fukumori/task/sp`のほうが綺麗に見える。
上記理由で～.htmlで表示するwebページはあまり多くないです。

変更前
students/k_fukumori/task/index_sp.html
↓
変更後
students/k_fukumori/task/sp/index.html

2022-01-19 15:15 UTC, kfukumori commented
ディレクトリの構造を修正しましたのでご確認お願いいたします。

2022-01-20 02:08 UTC, kyosuke-oki-adglobe-co-jp requested changes

2022-01-20 02:08 UTC, kyosuke-oki-adglobe-co-jp commented on students/k_fukumori/task/sp/index.html
> +        <li><!-- <a href=""> -->Contact</a></li>
[must]aタグの閉じタグだけ残っているので削除しておいてください。
コメントアウトでタグを残しておきたい場合は下記のようにするといいと思います。
```

        <!-- TODO: aタグを付与してページ内リンク機能を作成する -->
   <!-- <li><a href="">About</a></li>
        <li><a href="">Service</a></li>
        <li><a href="">Contents</a></li>
        <li><a href="">Contact</a></li> -->

        <li>About</li>
        <li>Service</li>
        <li>Contents</li>
        <li>Contact</li>
```

2022-01-26 02:36 UTC, kyosuke-oki-adglobe-co-jp commented
大変だったと思いますが、メニューいい感じに出来てきましたね！
LGTMです！

2022-01-26 02:36 UTC, kyosuke-oki-adglobe-co-jp approved these changes

2022-01-26 02:36 UTC, merged